### ISSUE TITLE
Hey，Fox2Code，I really support to you

### ISSUE THREAD

**Issue by wdog5** [Fox2Code/PuzzleModLoader#1]
I hope you can work on it，Sir

**Comment by Fox2Code** [comment]
I can't work on it due to my health issues
If I stopped to work on it it's not because I don't want it's because I can't
I really wish I could work on it too

Anyways thank for the support and the help

**Comment by wdog5** [comment]
Sorry，alas，I feel so painful that you cannot work on it

**Comment by Fox2Code** [comment]
@1798643961 
You can have write access to this repo directly if you want
https://github.com/Fox2Code/PuzzleModLoader/invitations
